// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyBudgetApp.Data;

#nullable disable

namespace MyBudgetApp.Data.Migrations
{
    [DbContext(typeof(BudgetDbContext))]
    [Migration("20260315022007_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyBudgetApp.Core.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)")
                        .HasDefaultValue("#6c757d");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#28a745",
                            Name = "Salary"
                        },
                        new
                        {
                            Id = 2,
                            Color = "#fd7e14",
                            Name = "Food & Dining"
                        },
                        new
                        {
                            Id = 3,
                            Color = "#17a2b8",
                            Name = "Transport"
                        },
                        new
                        {
                            Id = 4,
                            Color = "#6610f2",
                            Name = "Rent & Housing"
                        },
                        new
                        {
                            Id = 5,
                            Color = "#dc3545",
                            Name = "Healthcare"
                        },
                        new
                        {
                            Id = 6,
                            Color = "#e83e8c",
                            Name = "Entertainment"
                        },
                        new
                        {
                            Id = 7,
                            Color = "#007bff",
                            Name = "Education"
                        },
                        new
                        {
                            Id = 8,
                            Color = "#ffc107",
                            Name = "Shopping"
                        },
                        new
                        {
                            Id = 9,
                            Color = "#6c757d",
                            Name = "Utilities"
                        },
                        new
                        {
                            Id = 10,
                            Color = "#343a40",
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("MyBudgetApp.Core.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("MyBudgetApp.Core.Models.Transaction", b =>
                {
                    b.HasOne("MyBudgetApp.Core.Models.Category", "Category")
                        .WithMany("Transactions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MyBudgetApp.Core.Models.Category", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
